---
sudoers_custom_config: |
  %sudo ALL=(ALL) NOPASSWD: ALL
apt_packages:
- snapper-gui
- gh
- fish
- byobu
- fzf
- httpie
- htop
- dstat
- tree
- yt-dlp
- emacs-gtk
- vagrant
- tldr
- imagemagick
- neofetch
- ssh
- gnome-boxes
- gnome-tweaks
- gstreamer1.0-libav
- gstreamer1.0-plugins-bad
