---
sudoers_custom_config: |
  %sudo ALL=(ALL) NOPASSWD: ALL
apt_packages:
- snapper-gui
- gh
- fish
- byobu
- fzf
- httpie
- htop
- dstat
- tree
- yt-dlp
- emacs-gtk
- virtualbox-qt
- vagrant
- tldr
- imagemagick
