---
sudoers_custom_config: |
  %sudo ALL=(ALL) NOPASSWD: ALL
flatpak_packages:
- https://flathub.org/beta-repo/appstream/org.gimp.GIMP.flatpakref
- org.inkscape.Inkscape
- org.kde.krita
- md.obsidian.Obsidian
apt_packages:
- snapper-gui
- gh
- fish
- byobu
- fzf
- httpie
- htop
- dstat
- tree
- emacs-gtk
- tldr
- imagemagick
- neofetch
- ssh
- gnome-tweaks
- gstreamer1.0-libav
- gstreamer1.0-plugins-bad
- ibus-mozc
- mozc-utils-gui
- hwloc
- obs-studio
- remmina
- remmina-plugin-rdp
- remmina-plugin-vnc
- freerdp2-x11
- guestfs-tools
- direnv
- borgbackup
- vorta
apt_packages_remove:
- totem
