---
- name: Run root tasks
  hosts: all
  connection: local
  become: yes
  vars_files:
    - default.config.yaml
  roles:
    - darkwizard242.googlechrome
    - baztian.jetbrains_toolbox
    - dyindude.discord
    - role: geerlingguy.docker
      docker_users:
        - shuuji3
  tasks:
    - include_tasks: tasks/hostname.yaml
    - include_tasks: tasks/sudoers.yaml
    - include_tasks: tasks/install-packages.yaml
    - include_tasks: tasks/install-btrfs-assistant.yaml
    - include_tasks: tasks/chsh-fish.yaml
    - include_tasks: tasks/setup-starship.yaml
    - include_tasks: tasks/install-slack-app.yaml
    - include_tasks: tasks/install-incus.yaml
    - include_tasks: tasks/install-vagrant-with-libvirt.yaml
    - include_tasks: tasks/install-google-cloud-sdk.yaml
    - include_tasks: tasks/install-yt-dlp.yaml
    - include_tasks: tasks/install-google-drive-ocamlfuse.yaml
    - include_tasks: tasks/install-terraform.yaml
- name: Run user tasks
  hosts: all
  connection: local
  vars_files:
    - default.config.yaml
  roles:
    - role: agoloncser.pyenv
      pyenv_python_versions:
      - version: 3.11.5
        global: yes
    - pddg.xkeysnail
  tasks:
    - include_tasks: tasks/setup-chezmoi.yaml
    - include_tasks: tasks/install-fonts.yaml
    - include_tasks: tasks/setup-ssh.yaml
