---
- name: Run root tasks
  hosts: all
  connection: local
  become: yes
  vars_files:
    - default.config.yaml
  roles:
    - darkwizard242.googlechrome
    - baztian.jetbrains_toolbox
  tasks:
    - include_tasks: tasks/sudoers.yaml
    - include_tasks: tasks/install-apt-packages.yaml
    - include_tasks: tasks/install-btrfs-assistant.yaml
- name: Run user tasks
  hosts: all
  connection: local
  vars_files:
    - default.config.yaml
  tasks:
    - include_tasks: tasks/setup-chezmoi.yaml
