---
- name: Run root tasks
  hosts: all
  connection: local
  become: yes
  vars_files:
    - default.config.yaml
  roles:
    - darkwizard242.googlechrome
    - baztian.jetbrains_toolbox
  tasks:
    - include_tasks: tasks/sudoers.yaml
    - include_tasks: tasks/install-apt-packages.yaml
    - include_tasks: tasks/install-btrfs-assistant.yaml
    - include_tasks: tasks/chsh-fish.yaml
    - include_tasks: tasks/setup-starship.yaml
    - include_tasks: tasks/install-slack-app.yaml
- name: Run user tasks
  hosts: all
  connection: local
  vars_files:
    - default.config.yaml
  roles:
    - role: agoloncser.pyenv
      pyenv_python_versions:
      - version: 3.11.5
  tasks:
    - include_tasks: tasks/setup-chezmoi.yaml
