---
roles:
  - baztian.jetbrains_toolbox
  - darkwizard242.googlechrome
  - agoloncser.pyenv
  - dyindude.discord
  - geerlingguy.docker
  - pddg.xkeysnail
  - Comcast.sdkman
  - artis3n.tailscale
  - buluma.virtualbox
collections:
  - community.general
  - ansible.posix
