---
packages:
  - ssh
  - vino
  - gnome-tweaks
  - flatpak
  - autokey-gtk
  - cargo
  - ibus-mozc
  - mozc-utils-gui
  - gimp
  - rbenv
  - virtualbox-qt
  - jq
  - fish
  - vagrant
  - rclone-browser
  - ffmpeg
  - v4l2loopback-dkms
  - imagemagick
  - encfs
  - iostat
  - picard
snap_packages:
  - name: tree
  - name: htop
  - name: lxd
  - name: microk8s
    classic: yes
  - name: multipass
    classic: yes
    channel: beta
  - name: emacs
    classic: yes
  - name: hub
    classic: yes
  - name: teams-for-linux
  - name: node
    channel: 13/stable
    classic: yes
  - name: google-cloud-sdk
    classic: yes
  - name: gimp
  - name: zoom-client
  - name: obs-studio
  - name: youtube-dl
homebrew_packages:
  - kubectl
  - kind
  - helm
  - terraform
  - gh
  - ccat
  - kompose
  - go
  - poetry
  - awscli
flatpak_packages: []
npm_global_packages:
  - yarn
