---
- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"
- name: install snap packages
  snap:
    name: "{{ item.name | default(omit) }}"
    classic: "{{ item.classic | default(omit) }}"
    channel: "{{ item.channel | default(omit) }}"
  with_items: "{{ snap_packages }}"
