---
- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"
- name: install snap packages
  snap:
    name: "{{ item.name | default(omit) }}"
    classic: "{{ item.classic | default(omit) }}"
    channel: "{{ item.channel | default(omit) }}"
  with_items: "{{ snap_packages }}"
- name: add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
- name: install flatpak packages
  flatpak:
    name: "{{ item }}"
  with_items: "{{ flatpak_packages }}"
