---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

#dotfiles_repo: https://github.com/shuuji3/dotfiles.git
#dotfiles_repo_accept_hostkey: true
#dotfiles_repo_local_destination: ~/src/dotfiles
#dotfiles_files:
#  - .zshrc
#  - .gitignore
#  - .inputrc
#  - .osx
#  - .vimrc

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  #  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  #  - iperf # could not be installed in M1 mac
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - nvm
  #  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  #  - wrk # could not be installed in M1 mac
  #  - encfs # could not be installed in M1 mac
  - fish
  - emacs
  - youtube-dl
  - git-filter-repo
  - infracost
  - google-cloud-sdk
  - htop
  - tree
  - jq
  - kind
  - minikube
  - wasmer
  - rustup
  - k3sup
  - byobu
  - ccat
  - terraform
  - helm
  - skaffold
  - krew
  - tldr
  - yarn
  - iproute2mac
  - buildpacks/tap/pack
  - starship
  - xxh
  - hugo
  - font-jetbrains-mono-nerd-font
  - svn
  - font-roboto
  - font-roboto-mono
  - ffmpeg
  - fzf
  - argocd
  - k3d
  - ngrok
  - alexellis/homebrew-alexellis/arkade
  - atlantis
  - act
  - colordiff
  - ghostunnel
  - cfssl
  - yq
  - inkscape
  - zotero
  - commitizen
  - arduino
  - git-delta
  - bat
  - zoxide
  - ripgrep
  - asdf
  - heroku/brew/heroku

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - firefox
  - google-chrome
  - google-chrome-canary
  - handbrake
  - slack
  - vagrant
  - macfuse
  - discord
  - microsoft-teams
  - zoom
  - visual-studio-code
  - barrier
  - amethyst
  - obs
  - appcleaner
  - typora
  - pomello
  - flutter
  - grandperspective
  - alfred
  - blender
  - burp-suite
  - iina
  - utm
  - raspberry-pi-imager
  - google-web-designer
  - google-japanese-ime
  - google-earth-pro
  - qgis
  - blackhole-2ch
  - signal
  - telegram
  - element
  - cue-lang/tap/cue
  - gather

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { "id": 497799835, "name": "Xcode (13.1)" }
  - { "id": 1423210932, "name": "Flow (2.7.5)" }
  - { "id": 1452453066, "name": "Hidden Bar (1.8)" }
  - { "id": 1475387142, "name": "Tailscale (1.16.1)" }
mas_email: "shuuji3@gmail.com"
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: zx
  - name: node-red
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
  - name: ansible
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
