---
- name: Install flatpak packages
  flatpak:
    name: "{{ item.name | default(item) }}"
  loop: "{{ flatpak_packages }}"
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install apt packages
  apt:
    name: "{{ item.name | default(item) }}"
  loop: "{{ apt_packages }}"
