---
- name: Install vagrant
  apt:
    name: vagrant
- name: Install libvirt systemd service
  apt:
    name: libvirt-daemon-system
- name: Install virt-manager application to manage VMs
  apt:
    name: virt-manager
- name: Add user to libvirt group
  user:
    append: yes
    name: shuuji3
    groups: libvirt
