---
- name: Add gpg key
  get_url:
    url: https://pkgs.zabbly.com/key.asc
    dest: /etc/apt/keyrings/zabbly.asc
- name: Prepare apt repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/zabbly.asc] https://pkgs.zabbly.com/incus/stable {{ ansible_distribution_release }} main"
    filename: incus
- name: Install incus
  apt:
    update_cache: yes
    name: incus
- name: Add user to incus-admin group
  user:
    append: yes
    name: shuuji3
    groups: incus-admin
