---
- name: Install flatpak packages
  loop: "{{ flatpak_packages }}"
  flatpak:
    name: "{{ item.name | default(item) }}"
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install apt packages
  loop: "{{ apt_packages }}"
  apt:
    name: "{{ item.name | default(item) }}"
- name:  Uninstall apt packages
  loop: "{{ apt_packages_remove }}"
  apt:
    name: "{{ item.name | default(item) }}"
    state: absent
