---
- name: Configure NFS Server
  hosts: nfs_servers
  become: yes

  tasks:
  - name: Ensure nfs-kernel-server package is installed
    apt:
      name: nfs-kernel-server
      state: present
      update_cache: yes

  - name: Ensure /etc/exports.d directory exists
    ansible.builtin.file:
      path: /etc/exports.d
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Create NFS shared directory for each client
    ansible.builtin.file:
      path: "/srv/nfs/{{ hostvars[item].nfs_export_name }}"
      state: directory
      mode: '0755'
      owner: nobody
      group: nogroup
    loop: "{{ groups['nfs_clients'] }}"

  - name: Add NFS export entry for each client as a separate file
    ansible.builtin.template:
      src: nfs_exports.j2
      dest: "/etc/exports.d/{{ hostvars[item].nfs_export_name }}.exports"
      owner: root
      group: root
      mode: '0644'
    loop: "{{ groups['nfs_clients'] }}"
    notify:
    - Restart nfs-kernel-server

  - name: Ensure nfs-kernel-server service is running and enabled
    service:
      name: nfs-kernel-server
      state: started
      enabled: yes

  handlers:
  - name: Restart nfs-kernel-server
    service:
      name: nfs-kernel-server
      state: restarted
